version: '3.1'

services:

  netmon-user-web-app:
    build: Services/UserWebApp
    container_name: netmon-user-web-app
    environment:
      - ENV=production
      - ORIGIN=http://localhost:80
    ports:
      - "80:3000"

  netmon-admin-web-app:
    build: Services/AdminWebApp
    container_name: netmon-admin-web-app
    environment:
      - ENV=production
      - ORIGIN=http://localhost:81
    ports:
      - "81:3000"

  netmon-api-gateway:
    build: Services/APIGateway
    container_name: netmon-api-gateway
    environment:
      - ENV=production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"

  netmon-account-service:
    build: Services/AccountService
    container_name: netmon-account-service
    environment:
      - ENV=production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"

  netmon-device-manager-service:
    build:
      context: ./
      dockerfile: ./Services/Netmon.DeviceManager/Dockerfile
    container_name: netmon-device-manager-service
    environment:
      - ENV=production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"
    depends_on:
      - netmon-mongo
      - netmon-mysql
      - netmon-snmp-polling-service

  netmon-snmp-polling-service:
    build:
      context: ./
      dockerfile: ./Services/Netmon.SNMPPolling/Dockerfile
    container_name: netmon-snmp-polling-service
    environment:
      - ENV=production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5003:80"
    depends_on:
      - netmon-mysql

  netmon-snmp-test-agent:
    build: Tests/SNMPTestAgent
    container_name: netmon-snmp-test-agent
    hostname: snmpd-test
    ports:
      - "161:161/udp"

  netmon-mongo:
    image: mongo
    container_name: netmon-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  netmon-mongo-web-viewer:
    image: mongo-express
    container_name: netmon-mongo-web-viewer
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_URL: mongodb://root:mongopwd@192.168.178.8:27017/
    links:
      - netmon-mongo
    depends_on:
      - netmon-mongo

  netmon-mysql:
    image: mysql
    container_name: netmon-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3110:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: devices
      MYSQL_USER: user
      MYSQL_PASSWORD: pass